name = "booking-worker-py-be"
main = "src/worker.py"
compatibility_date = "2025-08-14"
compatibility_flags = ["python_workers"]

workers_dev = true

[vars]
MESSAGE = "CUSTOM_ENV_VARIABLE_MESSAGE"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"                  
database_name = "booking-db"     
database_id = "392dd2e1-3b69-4fa4-8408-10ecee89bb54"